node('master') {
  stage('do something with git') {  
    sshagent (credentials: ['github-ssh-agent']) {
      // get the last commit id from a repository you own
      sh 'git ls-remote -h --refs git@github.com:rustamsariyev/jenkins-course.git master |awk "{print $1}"'
    }
  }
}
